### ISSUE TITLE
display: 'flex' doesn't work on device mode

### ISSUE THREAD

**Issue by YesaDyuss** [rofrischmann/inline-style-prefixer#38] opened 2015-12-24 04:26 UTC
https://github.com/FormidableLabs/radium/issues/467

**Comment by rofrischmann** [comment] 2015-12-24 10:02
To sum it up
Windows: 10
Browser: Chrome Version 47.0.2526.106
device: Chrome - inspect - toggle device mode

Can you give me the exact userAgent when devices are toggled?
Also I'd like to know which device view you're toggling. Perhaps you're using e.g. an Android Phone with a specified Android userAgent that actually needs the `webkit-box` old spec (e.g. Android < 4.4)

**Comment by YesaDyuss** [comment] 2015-12-24 10:16
On google device mode inspect in every device i have the same problem: Im sending display: 'flex',
instead i got display: '-webkit-box'
![webkitbox](https://cloud.githubusercontent.com/assets/13980806/11993287/401699ac-aa59-11e5-9738-321317be9449.png)

Thank you for attention!

**Comment by rofrischmann** [comment] 2015-12-24 12:14
Hmm, can you please send me the full userAgent used there? I am not using Chrome nor have it installed on my machine :P

**Comment by kylefinley** [comment] 2016-01-02 18:34
I believe I'm seeing a similar issue in:
- Safari device mode `600 x 800` and Chrome device mode when setting the User Agent to: `Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.0; Trident/4.0)`
- iOS in app browsers like **Twitter** & **Facebook** Apps. They try to open links in their own built in browser, instead of opening Safari. I think they might be using a generic User Agent, I'll try to determine the exact string. 

I think the root cause is that `inline-style-prefix` is sending only the `-ms-flex` styles and not sending the `display: flex` rules.

I'm looking through the code now, but I believe support for multiple rules was added in this issue (https://github.com/rofrischmann/inline-style-prefixer/issues/2#issuecomment-131463165) correct?

**Comment by rofrischmann** [comment] 2016-01-02 18:43
@kylefinley For the first example: Setting the userAgent to IE 8 will lead to IE 8 specific prefixes (which ofc it exactly what it should do), but as you're still within Safari and therefore using WebKit's renderer, it does not work as it needs the `-webkit-flex` or just `flex`.
But I think that is not a problem of inline-style-prefixer as it works correctly and the problem is only caused by the developer himself changing the userAgent. 

The second example on the other hand seems quite interesting, as this is a very specific use-case and I never tested that before. Would love to have your support here to solve that!

### About multi values:
Yep it actually supports those, but I removed those completely to achieve the minimum of styles possible. Could have some kind of configuration bool which can be set, to also add default values if you'd wish to.

**Comment by kylefinley** [comment] 2016-01-02 18:57
@rofrischmann 
Thank you for you quick reply.

Yes, the first issue I'm not concerned with. The second issue was brought up by a client, so I'm trying to reproduce it now.

Adding a config bool would be great. Depending upon the overhead, maybe always sending the standard values, would be prudent as well. 

I appreciate your work on this, it's a tough problem. There's a lot of trickery that goes into user agents. I'll post back here once I've determined the UAs

**Comment by rofrischmann** [comment] 2016-01-03 00:34
@kylefinley `keepDefault` has been implemented.

For device mode testing I would recommend to use it or even use `prefixAll` which automatically uses `keepDefault`. Version 0.6 has been released btw. :) 

I will close this issue for now
@kylefinley Would be nice if you could open a seperate one after getting info on those in app userAgents

**Closed by rofrischmann** 2016-01-03 00:34 UTC
