### ISSUE TITLE
"TypeError: null is not an object" in Mobile Safari 8 when using custom static build

### ISSUE THREAD

**Issue by necolas** [rofrischmann/inline-style-prefixer#143] opened 2017-08-09 18:08 UTC
Hey, I created a custom static build and we have started to see errors in production that originate within `inline-style-prefixer`

Browser: Mobile Safari 8.0 (iPhone and iPad)
OS: iOS 8.0 and iOS 8.1

```
TypeError: null is not an object

~/inline-style-prefixer/static/plugins/crossFade.js in obj at line 12:38
L8: var _isPrefixedValue = require('css-in-js-utils/lib/isPrefixedValue');
L10: var _isPrefixedValue2 = _interopRequireDefault(_isPrefixedValue);
L12: function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

~/inline-style-prefixer/static/plugins/crossFade.js in Object at line 3:0
L3: Object.defineProperty(exports, "__esModule", { value: true });
```

* [Generator script](https://github.com/necolas/react-native-web/blob/master/scripts/createPrefixer.js)
* [Output](https://github.com/necolas/react-native-web/blob/master/src/modules/prefixStyles/static.js)

**Comment by rofrischmann** [comment] 2017-08-09 18:41
Hmm, looks like the generated output is fine. But I don't really get the errors (it fails on Babel-compiled code?)

**Comment by rofrischmann** [comment] 2017-10-15 10:52
Seems like I can't really reproduce this. Closing for now

**Closed by rofrischmann** 2017-10-15 10:52 UTC
